POP_SIZE = 50

PERCENT_TO_SAVE = 0.1

NODE_MUTATION_CHANCE = 0.1
CONNECTION_MUTATION_CHANCE = 0.5
ENABLE_DISABLE_CHANCE = 0.5

MUTATION_TRIES = 100  # number of tries a mutation gets to pick acceptable individual

MIN_CHILDREN_PER_SPECIES = 2
ELITE_TO_KEEP = 5

SPECIES_DISTANCE_THRESH = 1
SPECIES_DISTANCE_THRESH_MOD = 0.15
TARGET_NUM_SPECIES = 4
