POP_SIZE = 20

PERCENT_TO_SAVE = 0.2

NODE_MUTATION_CHANCE = 0.1
CONNECTION_MUTATION_CHANCE = 0.5
ENABLE_DISABLE_CHANCE = 0.5

MUTATION_TRIES = 100  # number of tries a mutation gets to pick acceptable individual

MIN_CHILDREN_PER_SPECIES = 2
ELITE_TO_KEEP = 5

DISTANCE_THRESH = 3
